-- Delete existing exercises for the Italian episode
DELETE FROM exercises WHERE episode_id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';

-- Insert comprehensive exercise sets for Italian TV History episode
-- A1 LEVEL - SET 1: COMPREHENSION (10 questions)
INSERT INTO exercises (episode_id, exercise_type, question, options, correct_answer, explanation, difficulty, xp_reward, order_index) VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Cosa parla questo podcast?', '["La storia della televisione italiana", "La storia del cinema italiano", "La storia della radio italiana", "La storia dei giornali italiani"]', 'La storia della televisione italiana', 'Il podcast parla della storia della televisione in Italia, dalle sue origini ai giorni nostri.', 'A1', 10, 1),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Quando è nata la televisione in Italia?', '["Negli anni 1950", "Negli anni 1940", "Negli anni 1960", "Negli anni 1930"]', 'Negli anni 1950', 'La televisione italiana è nata ufficialmente negli anni 1950 con la RAI.', 'A1', 10, 2),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'true_false', 'La RAI è stata la prima televisione italiana.', '["Vero", "Falso"]', 'Vero', 'Sì, la RAI (Radiotelevisione Italiana) è stata la prima emittente televisiva in Italia.', 'A1', 10, 3),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Che cosa significa RAI?', '["Radiotelevisione Italiana", "Radio Italiana", "Televisione Italiana", "Rete Italiana"]', 'Radiotelevisione Italiana', 'RAI è l\'acronimo di Radiotelevisione Italiana, il servizio pubblico radiotelevisivo italiano.', 'A1', 10, 4),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Quanti canali aveva la televisione italiana all\'inizio?', '["Uno", "Due", "Tre", "Quattro"]', 'Uno', 'All\'inizio la televisione italiana aveva solo un canale, Rai 1 (allora chiamato Programma Nazionale).', 'A1', 10, 5),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'true_false', 'All\'inizio poche famiglie avevano la televisione.', '["Vero", "Falso"]', 'Vero', 'Negli anni \'50 la televisione era un lusso e poche famiglie potevano permettersela.', 'A1', 10, 6),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Dove guardavano la televisione le persone senza TV?', '["Nei bar", "Nelle chiese", "Nelle scuole", "Nei parchi"]', 'Nei bar', 'Molte persone senza televisione si riunivano nei bar per guardare i programmi insieme.', 'A1', 10, 7),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Che tipo di programmi c\'erano all\'inizio?', '["Programmi semplici", "Programmi molto complicati", "Solo film", "Solo notizie"]', 'Programmi semplici', 'I primi programmi televisivi erano semplici: notizie, varietà e alcuni programmi educativi.', 'A1', 10, 8),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'true_false', 'La televisione ha cambiato la vita degli italiani.', '["Vero", "Falso"]', 'Vero', 'La televisione ha profondamente trasformato la società italiana, influenzando cultura, lingua e abitudini.', 'A1', 10, 9),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'La televisione italiana è diventata più popolare negli anni...', '["1960", "1940", "1970", "1980"]', '1960', 'Negli anni \'60 la televisione si diffuse rapidamente nelle case italiane.', 'A1', 10, 10),

-- A1 LEVEL - SET 2: VOCABULARY (10 questions)
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'fill_blank', 'La _______ è un mezzo di comunicazione molto importante.', '["televisione"]', 'televisione', 'La televisione è un mezzo di comunicazione di massa che trasmette immagini e suoni.', 'A1', 10, 11),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Cosa significa "trasmettere"?', '["Mandare in onda", "Comprare", "Vendere", "Rompere"]', 'Mandare in onda', 'Trasmettere significa mandare in onda, diffondere programmi televisivi o radiofonici.', 'A1', 10, 12),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'fill_blank', 'Un _______ è una storia che si guarda in televisione.', '["programma"]', 'programma', 'Un programma televisivo è un contenuto organizzato che viene trasmesso in TV.', 'A1', 10, 13),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Che cosa è un "canale"?', '["Una stazione televisiva", "Un tipo di cibo", "Un animale", "Una macchina"]', 'Una stazione televisiva', 'Un canale è una stazione televisiva che trasmette programmi specifici.', 'A1', 10, 14),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'fill_blank', 'Le _______ sono informazioni importanti che si sentono in TV.', '["notizie"]', 'notizie', 'Le notizie sono informazioni su eventi attuali che vengono trasmesse nei telegiornali.', 'A1', 10, 15),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Cosa significa "pubblico"?', '["Le persone che guardano", "I soldi", "La casa", "Il lavoro"]', 'Le persone che guardano', 'Il pubblico sono le persone che guardano i programmi televisivi.', 'A1', 10, 16),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'fill_blank', 'Negli anni \'50 la televisione era un _______.', '["lusso"]', 'lusso', 'Un lusso è qualcosa di costoso che non tutti possono permettersi.', 'A1', 10, 17),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Cosa significa "diffondere"?', '["Espandere, far conoscere", "Nascondere", "Dimenticare", "Perdere"]', 'Espandere, far conoscere', 'Diffondere significa far conoscere qualcosa a molte persone, espandere.', 'A1', 10, 18),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'fill_blank', 'Le _______ italiane hanno iniziato a comprare la televisione negli anni \'60.', '["famiglie"]', 'famiglie', 'Le famiglie sono gruppi di persone che vivono insieme, generalmente genitori e figli.', 'A1', 10, 19),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'multiple_choice', 'Cosa significa "varietà" nei programmi TV?', '["Spettacoli con musica e comicità", "Solo notizie", "Solo film", "Solo sport"]', 'Spettacoli con musica e comicità', 'I programmi di varietà sono spettacoli che combinano musica, danza, comicità e intrattenimento.', 'A1', 10, 20);