
-- Update absolute_beginner flashcards with multi-language translations
UPDATE onboarding_videos SET flashcards = '[
  {"phrase":"luggage","translation":{"en":"Bags and suitcases you travel with","es":"Bolsas y maletas con las que viajas","pt":"Malas e bolsas com as quais você viaja","fr":"Sacs et valises avec lesquels vous voyagez","it":"Borse e valigie con cui viaggi"},"why":{"en":"Essential travel vocabulary","es":"Vocabulario esencial de viaje","pt":"Vocabulário essencial de viagem","fr":"Vocabulaire de voyage essentiel","it":"Vocabolario essenziale di viaggio"}},
  {"phrase":"trunk","translation":{"en":"The back storage area of a car","es":"El maletero del coche","pt":"O porta-malas do carro","fr":"Le coffre de la voiture","it":"Il bagagliaio della macchina"},"why":{"en":"Used when putting bags in a taxi or car","es":"Se usa al poner bolsas en un taxi o coche","pt":"Usado ao colocar malas em um táxi ou carro","fr":"Utilisé pour mettre des sacs dans un taxi ou une voiture","it":"Usato per mettere le borse in un taxi o in macchina"}},
  {"phrase":"highway","translation":{"en":"A fast, main road between cities","es":"Una carretera rápida y principal entre ciudades","pt":"Uma estrada rápida e principal entre cidades","fr":"Une route rapide et principale entre les villes","it":"Una strada veloce e principale tra le città"},"why":{"en":"Common word when discussing routes","es":"Palabra común al hablar de rutas","pt":"Palavra comum ao discutir rotas","fr":"Mot courant pour parler de trajets","it":"Parola comune quando si parla di percorsi"}},
  {"phrase":"traffic","translation":{"en":"Cars and vehicles on the road causing delays","es":"Coches y vehículos en la carretera causando retrasos","pt":"Carros e veículos na estrada causando atrasos","fr":"Voitures et véhicules sur la route causant des retards","it":"Auto e veicoli sulla strada che causano ritardi"},"why":{"en":"Important for understanding travel times","es":"Importante para entender los tiempos de viaje","pt":"Importante para entender os tempos de viagem","fr":"Important pour comprendre les temps de trajet","it":"Importante per capire i tempi di viaggio"}},
  {"phrase":"fasten","translation":{"en":"To close or secure something tightly","es":"Cerrar o asegurar algo firmemente","pt":"Fechar ou prender algo firmemente","fr":"Fermer ou attacher quelque chose solidement","it":"Chiudere o fissare qualcosa saldamente"},"why":{"en":"Used with seat belts and safety equipment","es":"Se usa con cinturones de seguridad y equipos de protección","pt":"Usado com cintos de segurança e equipamentos de proteção","fr":"Utilisé avec les ceintures de sécurité et les équipements de protection","it":"Usato con le cinture di sicurezza e le attrezzature di protezione"}}
]'::jsonb WHERE language = 'english' AND level = 'absolute_beginner';

-- Update beginner flashcards
UPDATE onboarding_videos SET flashcards = '[
  {"phrase":"report","translation":{"en":"To officially tell someone about a problem or event","es":"Informar oficialmente a alguien sobre un problema o evento","pt":"Informar oficialmente alguém sobre um problema ou evento","fr":"Signaler officiellement un problème ou un événement","it":"Segnalare ufficialmente un problema o un evento"},"why":{"en":"Used when filing complaints or informing authorities","es":"Se usa al presentar quejas o informar a las autoridades","pt":"Usado ao registrar reclamações ou informar as autoridades","fr":"Utilisé pour déposer des plaintes ou informer les autorités","it":"Usato per presentare reclami o informare le autorità"}},
  {"phrase":"document","translation":{"en":"An official paper with important information","es":"Un papel oficial con información importante","pt":"Um papel oficial com informações importantes","fr":"Un papier officiel avec des informations importantes","it":"Un documento ufficiale con informazioni importanti"},"why":{"en":"Essential for talking about IDs, passports, etc.","es":"Esencial para hablar de identificaciones, pasaportes, etc.","pt":"Essencial para falar sobre identidades, passaportes, etc.","fr":"Essentiel pour parler de pièces d identité, passeports, etc.","it":"Essenziale per parlare di documenti di identità, passaporti, ecc."}},
  {"phrase":"passport","translation":{"en":"An official document for international travel","es":"Un documento oficial para viajes internacionales","pt":"Um documento oficial para viagens internacionais","fr":"Un document officiel pour les voyages internationaux","it":"Un documento ufficiale per i viaggi internazionali"},"why":{"en":"Key vocabulary for travel and identification","es":"Vocabulario clave para viajes e identificación","pt":"Vocabulário chave para viagens e identificação","fr":"Vocabulaire clé pour les voyages et l identification","it":"Vocabolario chiave per viaggi e identificazione"}},
  {"phrase":"ID number","translation":{"en":"A unique number on your identification card","es":"Un número único en tu tarjeta de identificación","pt":"Um número único no seu cartão de identidade","fr":"Un numéro unique sur votre carte d identité","it":"Un numero unico sulla tua carta d identità"},"why":{"en":"Needed when dealing with official processes","es":"Necesario al tratar con procesos oficiales","pt":"Necessário ao lidar com processos oficiais","fr":"Nécessaire pour les démarches officielles","it":"Necessario per le procedure ufficiali"}},
  {"phrase":"copy","translation":{"en":"A duplicate of an original document","es":"Un duplicado de un documento original","pt":"Uma cópia de um documento original","fr":"Un duplicata d un document original","it":"Una copia di un documento originale"},"why":{"en":"Often needed for official paperwork","es":"A menudo necesario para trámites oficiales","pt":"Frequentemente necessário para documentação oficial","fr":"Souvent nécessaire pour les documents officiels","it":"Spesso necessario per le pratiche ufficiali"}}
]'::jsonb WHERE language = 'english' AND level = 'beginner';

-- Update intermediate flashcards
UPDATE onboarding_videos SET flashcards = '[
  {"phrase":"grocery store","translation":{"en":"A shop where you buy food and supplies","es":"Una tienda donde compras comida y suministros","pt":"Uma loja onde você compra comida e suprimentos","fr":"Un magasin où vous achetez de la nourriture et des fournitures","it":"Un negozio dove compri cibo e forniture"},"why":{"en":"Everyday vocabulary for shopping","es":"Vocabulario cotidiano para ir de compras","pt":"Vocabulário do dia a dia para compras","fr":"Vocabulaire quotidien pour les courses","it":"Vocabolario quotidiano per fare la spesa"}},
  {"phrase":"supplies","translation":{"en":"Things you need for a task or daily life","es":"Cosas que necesitas para una tarea o la vida diaria","pt":"Coisas que você precisa para uma tarefa ou vida diária","fr":"Choses dont vous avez besoin pour une tâche ou la vie quotidienne","it":"Cose di cui hai bisogno per un compito o la vita quotidiana"},"why":{"en":"Useful word for talking about what you need to buy","es":"Palabra útil para hablar de lo que necesitas comprar","pt":"Palavra útil para falar sobre o que você precisa comprar","fr":"Mot utile pour parler de ce que vous devez acheter","it":"Parola utile per parlare di ciò che devi comprare"}},
  {"phrase":"wound","translation":{"en":"An injury where the skin is broken","es":"Una herida donde la piel está rota","pt":"Um ferimento onde a pele está rompida","fr":"Une blessure où la peau est ouverte","it":"Una ferita dove la pelle è rotta"},"why":{"en":"Important for describing injuries","es":"Importante para describir lesiones","pt":"Importante para descrever lesões","fr":"Important pour décrire des blessures","it":"Importante per descrivere ferite"}},
  {"phrase":"hose","translation":{"en":"A flexible tube for carrying water","es":"Un tubo flexible para transportar agua","pt":"Um tubo flexível para transportar água","fr":"Un tuyau flexible pour transporter de l eau","it":"Un tubo flessibile per trasportare acqua"},"why":{"en":"Found in gardens and on fire trucks","es":"Se encuentra en jardines y camiones de bomberos","pt":"Encontrado em jardins e em caminhões de bombeiros","fr":"Trouvé dans les jardins et sur les camions de pompiers","it":"Si trova nei giardini e sui camion dei pompieri"}},
  {"phrase":"scraped","translation":{"en":"Rubbed skin against a rough surface causing injury","es":"Raspar la piel contra una superficie áspera causando lesión","pt":"Raspar a pele contra uma superfície áspera causando lesão","fr":"Frotter la peau contre une surface rugueuse causant une blessure","it":"Sfregare la pelle contro una superficie ruvida causando una ferita"},"why":{"en":"Common word for minor injuries from falls","es":"Palabra común para lesiones menores por caídas","pt":"Palavra comum para lesões leves por quedas","fr":"Mot courant pour les blessures légères dues aux chutes","it":"Parola comune per lesioni minori da cadute"}}
]'::jsonb WHERE language = 'english' AND level = 'intermediate';

-- Update advanced flashcards
UPDATE onboarding_videos SET flashcards = '[
  {"phrase":"vandals","translation":{"en":"People who deliberately damage property","es":"Personas que dañan propiedades deliberadamente","pt":"Pessoas que danificam propriedades deliberadamente","fr":"Personnes qui endommagent délibérément des biens","it":"Persone che danneggiano deliberatamente proprietà"},"why":{"en":"Used to describe people who destroy or deface things","es":"Se usa para describir personas que destruyen o dañan cosas","pt":"Usado para descrever pessoas que destroem ou danificam coisas","fr":"Utilisé pour décrire des personnes qui détruisent ou dégradent des choses","it":"Usato per descrivere persone che distruggono o deturpano cose"}},
  {"phrase":"masterpiece","translation":{"en":"An outstanding work of art or skill","es":"Una obra maestra de arte o habilidad","pt":"Uma obra-prima de arte ou habilidade","fr":"Un chef-d œuvre d art ou de savoir-faire","it":"Un capolavoro di arte o abilità"},"why":{"en":"Used to describe exceptional creative works","es":"Se usa para describir obras creativas excepcionales","pt":"Usado para descrever obras criativas excepcionais","fr":"Utilisé pour décrire des œuvres créatives exceptionnelles","it":"Usato per descrivere opere creative eccezionali"}},
  {"phrase":"mural","translation":{"en":"A large painting done directly on a wall","es":"Una gran pintura hecha directamente en una pared","pt":"Uma grande pintura feita diretamente em uma parede","fr":"Une grande peinture réalisée directement sur un mur","it":"Un grande dipinto fatto direttamente su un muro"},"why":{"en":"Key word for street art and public artwork","es":"Palabra clave para arte callejero y arte público","pt":"Palavra-chave para arte de rua e arte pública","fr":"Mot clé pour l art de rue et l art public","it":"Parola chiave per la street art e l arte pubblica"}},
  {"phrase":"defaced","translation":{"en":"Spoiled or damaged the appearance of something","es":"Estropeó o dañó la apariencia de algo","pt":"Estragou ou danificou a aparência de algo","fr":"A abîmé ou dégradé l apparence de quelque chose","it":"Ha rovinato o danneggiato l aspetto di qualcosa"},"why":{"en":"Often used when artwork or property is damaged","es":"Se usa a menudo cuando se daña una obra de arte o propiedad","pt":"Frequentemente usado quando uma obra de arte ou propriedade é danificada","fr":"Souvent utilisé quand une œuvre d art ou un bien est endommagé","it":"Spesso usato quando un opera d arte o una proprietà viene danneggiata"}},
  {"phrase":"barriers","translation":{"en":"Fences or obstacles to block access","es":"Vallas u obstáculos para bloquear el acceso","pt":"Cercas ou obstáculos para bloquear o acesso","fr":"Clôtures ou obstacles pour bloquer l accès","it":"Recinzioni o ostacoli per bloccare l accesso"},"why":{"en":"Used by authorities to protect or restrict areas","es":"Usadas por las autoridades para proteger o restringir áreas","pt":"Usadas pelas autoridades para proteger ou restringir áreas","fr":"Utilisées par les autorités pour protéger ou restreindre des zones","it":"Usate dalle autorità per proteggere o limitare aree"}}
]'::jsonb WHERE language = 'english' AND level = 'advanced';
